[{"id":995299992,"node_id":"R_kgDOO1MSmA","name":"django-vulnerability-CVE-2025-32873","full_name":"Apollo-R3bot/django-vulnerability-CVE-2025-32873","private":false,"owner":{"login":"Apollo-R3bot","id":148726450,"node_id":"U_kgDOCN1isg","avatar_url":"https://avatars.githubusercontent.com/u/148726450?v=4","url":"https://api.github.com/users/Apollo-R3bot","html_url":"https://github.com/Apollo-R3bot","type":"User","site_admin":false},"html_url":"https://github.com/Apollo-R3bot/django-vulnerability-CVE-2025-32873","description":"Django Security Issue (CVE-2025-32873)","fork":false,"url":"https://api.github.com/repos/Apollo-R3bot/django-vulnerability-CVE-2025-32873","created_at":"2025-06-03T09:16:38Z","updated_at":"2025-06-03T09:16:40Z","pushed_at":"2025-06-03T09:16:38Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1},{"id":995296012,"node_id":"R_kgDOO1MDDA","name":"cve-2024-3094","full_name":"valeriot30/cve-2024-3094","private":false,"owner":{"login":"valeriot30","id":30567406,"node_id":"MDQ6VXNlcjMwNTY3NDA2","avatar_url":"https://avatars.githubusercontent.com/u/30567406?v=4","url":"https://api.github.com/users/valeriot30","html_url":"https://github.com/valeriot30","type":"User","site_admin":false},"html_url":"https://github.com/valeriot30/cve-2024-3094","description":"A XZ backdoor vulnerability explained in details","fork":false,"url":"https://api.github.com/repos/valeriot30/cve-2024-3094","created_at":"2025-06-03T09:09:23Z","updated_at":"2025-06-03T09:13:45Z","pushed_at":"2025-06-03T09:13:44Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]